# Generated by Django 3.2 on 2021-05-06 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodgroup',
            name='pincode',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999999)]),
            preserve_default=False,
        ),
    ]
